theme: jekyll-theme-minimal
# theme: jekyll-text-theme
logo: /images/me.jpg
title: Santiago González Silot Portfolio - NLP Data Scientist
description: Brief portfolio with some of my Data Science projects that I developed during my career.
